// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file todo.proto (package todo.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file todo.proto.
 */
export const file_todo: GenFile = /*@__PURE__*/
  fileDesc("Cgp0b2RvLnByb3RvEgd0b2RvLnYxIh4KDkFkZFRhc2tSZXF1ZXN0EgwKBHRleHQYASABKAkiLgoPQWRkVGFza1Jlc3BvbnNlEhsKBHRhc2sYASABKAsyDS50b2RvLnYxLlRhc2siEQoPR2V0VGFza3NSZXF1ZXN0IjAKEEdldFRhc2tzUmVzcG9uc2USHAoFdGFza3MYASADKAsyDS50b2RvLnYxLlRhc2siHwoRRGVsZXRlVGFza1JlcXVlc3QSCgoCaWQYASABKAkiJQoSRGVsZXRlVGFza1Jlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgiNAoEVGFzaxIKCgJpZBgBIAEoCRIMCgR0ZXh0GAIgASgJEhIKCmNyZWF0ZWRfYXQYAyABKAMy2QEKC1RvZG9TZXJ2aWNlEj4KB0FkZFRhc2sSFy50b2RvLnYxLkFkZFRhc2tSZXF1ZXN0GhgudG9kby52MS5BZGRUYXNrUmVzcG9uc2UiABJBCghHZXRUYXNrcxIYLnRvZG8udjEuR2V0VGFza3NSZXF1ZXN0GhkudG9kby52MS5HZXRUYXNrc1Jlc3BvbnNlIgASRwoKRGVsZXRlVGFzaxIaLnRvZG8udjEuRGVsZXRlVGFza1JlcXVlc3QaGy50b2RvLnYxLkRlbGV0ZVRhc2tSZXNwb25zZSIAQhpaGHRvZG8tbGlzdC90b2RvL3YxO3RvZG92MWIGcHJvdG8z");

/**
 * @generated from message todo.v1.AddTaskRequest
 */
export type AddTaskRequest = Message<"todo.v1.AddTaskRequest"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message todo.v1.AddTaskRequest.
 * Use `create(AddTaskRequestSchema)` to create a new message.
 */
export const AddTaskRequestSchema: GenMessage<AddTaskRequest> = /*@__PURE__*/
  messageDesc(file_todo, 0);

/**
 * @generated from message todo.v1.AddTaskResponse
 */
export type AddTaskResponse = Message<"todo.v1.AddTaskResponse"> & {
  /**
   * @generated from field: todo.v1.Task task = 1;
   */
  task?: Task;
};

/**
 * Describes the message todo.v1.AddTaskResponse.
 * Use `create(AddTaskResponseSchema)` to create a new message.
 */
export const AddTaskResponseSchema: GenMessage<AddTaskResponse> = /*@__PURE__*/
  messageDesc(file_todo, 1);

/**
 * @generated from message todo.v1.GetTasksRequest
 */
export type GetTasksRequest = Message<"todo.v1.GetTasksRequest"> & {
};

/**
 * Describes the message todo.v1.GetTasksRequest.
 * Use `create(GetTasksRequestSchema)` to create a new message.
 */
export const GetTasksRequestSchema: GenMessage<GetTasksRequest> = /*@__PURE__*/
  messageDesc(file_todo, 2);

/**
 * @generated from message todo.v1.GetTasksResponse
 */
export type GetTasksResponse = Message<"todo.v1.GetTasksResponse"> & {
  /**
   * @generated from field: repeated todo.v1.Task tasks = 1;
   */
  tasks: Task[];
};

/**
 * Describes the message todo.v1.GetTasksResponse.
 * Use `create(GetTasksResponseSchema)` to create a new message.
 */
export const GetTasksResponseSchema: GenMessage<GetTasksResponse> = /*@__PURE__*/
  messageDesc(file_todo, 3);

/**
 * @generated from message todo.v1.DeleteTaskRequest
 */
export type DeleteTaskRequest = Message<"todo.v1.DeleteTaskRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message todo.v1.DeleteTaskRequest.
 * Use `create(DeleteTaskRequestSchema)` to create a new message.
 */
export const DeleteTaskRequestSchema: GenMessage<DeleteTaskRequest> = /*@__PURE__*/
  messageDesc(file_todo, 4);

/**
 * @generated from message todo.v1.DeleteTaskResponse
 */
export type DeleteTaskResponse = Message<"todo.v1.DeleteTaskResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message todo.v1.DeleteTaskResponse.
 * Use `create(DeleteTaskResponseSchema)` to create a new message.
 */
export const DeleteTaskResponseSchema: GenMessage<DeleteTaskResponse> = /*@__PURE__*/
  messageDesc(file_todo, 5);

/**
 * @generated from message todo.v1.Task
 */
export type Task = Message<"todo.v1.Task"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string text = 2;
   */
  text: string;

  /**
   * @generated from field: int64 created_at = 3;
   */
  createdAt: bigint;
};

/**
 * Describes the message todo.v1.Task.
 * Use `create(TaskSchema)` to create a new message.
 */
export const TaskSchema: GenMessage<Task> = /*@__PURE__*/
  messageDesc(file_todo, 6);

/**
 * @generated from service todo.v1.TodoService
 */
export const TodoService: GenService<{
  /**
   * @generated from rpc todo.v1.TodoService.AddTask
   */
  addTask: {
    methodKind: "unary";
    input: typeof AddTaskRequestSchema;
    output: typeof AddTaskResponseSchema;
  },
  /**
   * @generated from rpc todo.v1.TodoService.GetTasks
   */
  getTasks: {
    methodKind: "unary";
    input: typeof GetTasksRequestSchema;
    output: typeof GetTasksResponseSchema;
  },
  /**
   * @generated from rpc todo.v1.TodoService.DeleteTask
   */
  deleteTask: {
    methodKind: "unary";
    input: typeof DeleteTaskRequestSchema;
    output: typeof DeleteTaskResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_todo, 0);

